### ISSUE TITLE
How to add a widget-social-icons?

### ISSUE THREAD

**Issue by kiarafrobles** [iTimeTraveler/hexo-theme-hipaper#15]
How do I add a widget-social-icons. Particularly I want to add [Keybase ](http://keybase.io)and Email. For some reason my email icon does not work in the hipaper theme.

**Comment by iTimeTraveler** [comment]
Hello, @kiarafrobles 

These icons are from [Font-Awesome Icons](http://fontawesome.io/icons/), so the widget-social-icon's title which you want to add should use these [Font-Awesome Icons] as a reference. 

For example, if you want to add a Email icon. First, search `email` from [Font-Awesome Icons](http://fontawesome.io/icons/), then choose a suitable icon and **copy its name** as Hipaper's widget-social-icon's title.

In here, I choose `envelope` as my email icon, use it like this:

```yml
# Social Links
# Key is the name of FontAwsome icon.
# Value is the target link (E.g. GitHub: https://github.com/iTimeTraveler)
social:
  Github: https://github.com/iTimeTraveler
  Weibo: 
  Twitter: 
  Facebook: 
  Google-plus: 
  Instagram: 
  Envelope: mailto:example@gmail.com
```

So, There must be some icons can't find in [Font Awesome], like `Keybase`. This is bad but you could use some general icons instead of it.
