### ISSUE TITLE
如何改变博客页面最上端的黑色区域？能否颜色这类的？

### ISSUE THREAD

**Issue by KangChou** [iTimeTraveler/hexo-theme-hipaper#44]
链接：[http://kangchou001.cn/](url)

**Comment by arginsen** [comment]
路径:  hiero//source/css/hiero.css 

搜索，更改以下内容: 

```css
/* HEADER
----------------------------------------------- */
/* 背景颜色 */
.site-header {
	background: #16171b;
	}
/* 站点名颜色 */
.site-title a {
	color: #fff;
	}
/* 站点描述颜色 */ 
.site-description {
	color: #999;
	}
```
